---

- name: check firewalld service
  stat:
    path: /usr/lib/systemd/system/firewalld.service
  register: firewall_service

- name: disable firewalld service
  service:
    name: firewalld
    state: stopped
    enabled: no
  when: 
    - firewall_service.stat.exists