---


- name: add libselinux-python package 
  copy: 
    src:  libselinux-python-2.5-11.el7.x86_64.rpm
    dest: /tmp/libselinux-python-2.5-11.el7.x86_64.rpm

- name: install libselinux-python package
  yum:
    name: /tmp/libselinux-python-2.5-11.el7.x86_64.rpm
    state: present

- name: remove libselinux-python package 
  file: 
    path: /tmp/libselinux-python-2.5-11.el7.x86_64.rpm
    state: absent

- name: disable selinux
  selinux:
    state: disabled
