---

- name: add centos7 baseline repo
  copy:
    src:  centos7.repo
    dest: /etc/yum.repos.d/centos7.repo

- name: add yum-plugin-priorities package 
  copy: 
    src:  yum-plugin-priorities-1.1.31-42.el7.noarch.rpm
    dest: /tmp/yum-plugin-priorities-1.1.31-42.el7.noarch.rpm

- name: install yum-plugin-priorities package 
  yum:
    name: /tmp/yum-plugin-priorities-1.1.31-42.el7.noarch.rpm
    state: present

- name: remove yum-plugin-priorities package
  file: 
    path: /tmp/yum-plugin-priorities-1.1.31-42.el7.noarch.rpm
    state: absent
