---

- name: install redis
  yum:
    name: redis
    state: present

- name: enable redis
  service: 
    name: redis
    enabled: yes

- name: enable redis-sentinel
  service: 
    name: redis-sentinel
    enabled: yes

- name: mkdir for redis
  file:
    path: "{{ item }}"
    owner: redis
    group: redis
    mode: 0750
    state: directory
  with_items:
    - "{{ redis_workdir }}"
    - "{{ redis_workdir }}/log"

- name: mkdir for redis_sentinel
  file:
    path: "{{ item }}"
    owner: redis
    group: redis
    mode: 0750
    state: directory
  with_items:
    - "{{ redis_sentinel_workdir }}"
    - "{{ redis_sentinel_workdir }}/log"

- name: set redis config
  template:
    src: redis.conf.j2
    dest: /etc/redis.conf
    owner: redis
    group: root
    mode: 0640
    backup: yes

- name: set slave redis config
  lineinfile:
    path: /etc/redis.conf
    insertafter: '^dir /opt/redis'
    line: 'slaveof {{ redis_master }} {{ redis_port }}'
    owner: redis
    group: root
    mode: 0640
    backup: yes
  when:  ansible_default_ipv4.address  != redis_master

- name: set redis sentinel config
  template:
    src: redis-sentinel.conf.j2
    dest: /etc/redis-sentinel.conf
    owner: redis
    group: root
    mode: 0640
    backup: yes

- name: start redis
  service: 
    name: redis
    state: started

- name: start redis-sentinel
  service: 
    name: redis-sentinel
    state: started
